export const keyfile = process.env.WALLET_FILE_PATH || "key.json";
// HISTORICAL ARNS REWARDS
export const HISTORICAL_BASIC_NAME_REWARD = 200;
export const HISTORICAL_UNDERNAME_DATA_POINTER_SET_REWARD = 200;
export const HISTORICAL_OG_NAME_REWARD = 200;
export const HISTORICAL_ROOT_DATA_POINTER_SET_REWARD = 200;
export const HISTORICAL_BASIC_UNDERNAME_REWARD = 200;
export const HISTORICAL_MANY_UNDERNAMES_REWARD = 200;
export const HISTORICAL_CONTROLLER_REWARD = 200;

// HISTORICAL GATEWAY REWARDS
export const HISTORICAL_JOINED_GATEWAY_REWARD = 200;

export const BASIC_NAME_REWARD = 100;
export const BASIC_UNDERNAME_REWARD = 100;
export const ROOT_DATA_POINTER_SET_REWARD = 100;
export const UNDERNAME_DATA_POINTER_SET_REWARD = 100;
export const DEFAULT_ARNS_DATA_POINTER =
  "UyC5P5qKPZaltMmmZAWdakhlDXsBF6qmyrbWYFchRTk";
export const ZEALY_START_TIMESTAMP = 1711954647;
